[css-spec-shortname-1] https://github.com/w3c/csswg-drafts/issues/10537
w3c/csswg-drafts pull request #10538
Opened 2024-07-08 07:07 UTC by jogibear9988

[css-spec-shortname-1] https://github.com/w3c/csswg-drafts/issues/10537

A linked issue:
https://github.com/w3c/csswg-drafts/issues/10514

a firefox issue with a little bit of description:
https://bugzilla.mozilla.org/show_bug.cgi?id=1107559

a polyfill for the API
https://github.com/jogibear9988/getBoxQuadsPolyfill

2024-07-10 12:54 UTC, jogibear9988 commented
One issues atm:
My polyfill only works for 2D transformations, 3D with perspective do not work (yet). Have to figure out how to do this. Cause of that, also my spec only works for 2D. I've found some spect for the 3D matrix, wich then also could maybe reused: https://drafts.csswg.org/css-transforms-2/#accumulated-3d-transformation-matrix-computation

2025-05-12 10:07 UTC, SebastianZ commented
I think it makes more sense to add another option to `getBoxQuads()` to consider the transformed coordinates instead of introducing a separate function `getCompleteTransform()` for that.

I imagine something like `getBoxQuads({considerTransformations: true})`.

Sebastian

2025-05-12 11:09 UTC, jogibear9988 commented
> One issues atm: My polyfill only works for 2D transformations, 3D with perspective do not work (yet). Have to figure out how to do this. Cause of that, also my spec only works for 2D. I've found some spect for the 3D matrix, wich then also could maybe reused: https://drafts.csswg.org/css-transforms-2/#accumulated-3d-transformation-matrix-computation

should be fixed in current polyfill

2025-05-12 11:12 UTC, jogibear9988 commented
> I think it makes more sense to add another option to `getBoxQuads()` to consider the transformed coordinates instead of introducing a separate function `getCompleteTransform()` for that.
> 
> I imagine something like `getBoxQuads({considerTransformations: true})`.
> 
> Sebastian

it's in a extra method, cause it is used from the 3 other functions in the spec

2025-05-22 09:49 UTC, emilio requested changes
Thanks, this looks like a good start. Please look at how other specs (specially recent ones) use bikeshed in order to get the formatting and references correct. Also this needs to work in terms of nodes and boxes, not elements.

2025-05-22 09:49 UTC, emilio commented on cssom-view-1/Overview.bs
> +The helper method getCompleteTransform(anchestor) must run the following steps:
You need to get the element as a parameter, and use `<div algorithm>` for this for example:

```
<div algorithm="get the complete transform">
  In order to <dfn export>get the complete transform</dfn> of an node <var>node</var> relative to a node <var>ancestor</ancestor> ...
</div>

2025-05-22 09:49 UTC, emilio commented on cssom-view-1/Overview.bs
> +2. let transformationMatrix be the current transformation matrix of currentElement (https://www.w3.org/TR/css-transforms-2/#ctm)
Please use bikeshed references for this.

2025-05-22 09:49 UTC, emilio commented on cssom-view-1/Overview.bs
> +1. get the resulting matrix between the element and the document.defaultView via the algorithm defined in getCompleteTransform
All these algorithms need to be in terms of `node`s, as `GeometryUtils` also applies to text nodes and such.

2025-05-22 09:49 UTC, emilio commented on cssom-view-1/Overview.bs
> +   - 'content': x + border.leftWidth + padding.left, y + border.topWidth + padding.top
This is not actually based on the computed style but on the actual used padding box etc. Those boxes are defined already elsewhere and we should reuse the definitions.

2025-07-08 18:16 UTC, whimboo commented
Hi @jogibear9988, would you maybe have the time to follow-up on the review from Emilio? Thanks

2025-07-28 05:46 UTC, jogibear9988 commented on cssom-view-1/Overview.bs
> +1. get the resulting matrix between the element and the document.defaultView via the algorithm defined in getCompleteTransform
Is node correct? Or should it be "GeometryNode"?
<img width="757" height="87" alt="image" src="https://github.com/user-attachments/assets/b7dd425e-8d78-4dce-955d-bd01b5c1b483" />

2025-07-28 05:48 UTC, jogibear9988 commented on cssom-view-1/Overview.bs
> +2. let transformationMatrix be the current transformation matrix of currentElement (https://www.w3.org/TR/css-transforms-2/#ctm)
Where should I use a bikeshed reference? (Is there an editor wich helps in editing bs files)

2025-07-28 06:06 UTC, jogibear9988 commented on cssom-view-1/Overview.bs
> +   - 'content': x + border.leftWidth + padding.left, y + border.topWidth + padding.top
I don't really find where I should link to.
maybe: https://drafts.csswg.org/css2/#Computing_widths_and_margins

2025-07-28 06:10 UTC, jogibear9988 commented on cssom-view-1/Overview.bs
> +The helper method getCompleteTransform(anchestor) must run the following steps:
I don't get what you mean with this....
getCompleteTransform has a parameter, wich is anchestor

2025-07-28 06:15 UTC, jogibear9988 commented on cssom-view-1/Overview.bs
> +The helper method getCompleteTransform(anchestor) must run the following steps:
Added node to helper function

2025-07-28 13:08 UTC, Psychpsyo commented on cssom-view-1/Overview.bs
> +   - 'content': x + border.leftWidth + padding.left, y + border.topWidth + padding.top
> I don't really find where I should link to. maybe: https://drafts.csswg.org/css2/#Computing_widths_and_margins

Pretty sure those boxes are defined here: https://drafts.csswg.org/css-box-4/#box-edges

2025-07-28 13:49 UTC, jogibear9988 commented on cssom-view-1/Overview.bs
> +   - 'content': x + border.leftWidth + padding.left, y + border.topWidth + padding.top
Yeah, but I need to link to the Algorythm how they are calculated, or is this enough?

2025-07-28 14:21 UTC, Psychpsyo commented on cssom-view-1/Overview.bs
> +   - 'content': x + border.leftWidth + padding.left, y + border.topWidth + padding.top
> Yeah, but I need to link to the Algorythm how they are calculated, or is this enough?

There is no algorithm like that for these. They are defined in English instead. Browsers have algorithms internally that match those descriptions and can call into those when a spec says to do something with one of these boxes, so linking to their definitions is enough to unambiguously tell an implementer what needs to happen.

More modern specs like to define their concepts in terms of algorithms to derive them, because that makes implementation easier and leaves less room for creative (mis-)interpretation of the definition.

TL;DR: You want to link to a concept's definition when using it. Whether that is an algorithm or not doesn't matter.

2025-07-28 18:47 UTC, jogibear9988 commented
@emilio 
is it okay like now?

2025-08-14 15:55 UTC, emilio requested changes
This still needs a bit of work to get the spec into a reasonable shape, but looks in the right direction. Thanks!

2025-08-14 15:55 UTC, emilio commented on cssom-view-1/Overview.bs
> + 1. let currentElement be node.
currentNode, right? I think this should use `<var>current</var>` and other bikeshed markup to display properly.

2025-08-14 15:55 UTC, emilio commented on cssom-view-1/Overview.bs
> + <ol>
Do you really need the `<ol>`?

2025-08-14 15:55 UTC, emilio commented on cssom-view-1/Overview.bs
> +The helper method getCompleteTransform(node, anchestor) must run the following steps:
I think you should probably add a `<dfn>` so that you can reference this properly elsewhere.

2025-08-14 15:55 UTC, emilio commented on cssom-view-1/Overview.bs
> + 1. create an array as result container
`Let |result| be an empty [=list=] of [=DOMQuad=] objects.` etc, please look at existing bikeshed files to see how to make this work.

2025-08-14 15:55 UTC, emilio commented on cssom-view-1/Overview.bs
> + 2. for each css-fragment of the element run the following steps
of what element? Probably of `this`? Also fragment should link to a definition.

2025-08-14 15:55 UTC, emilio commented on cssom-view-1/Overview.bs
> +    1. Create a DOMRect of the Element with the x,y value of 0 and the offsetWith and offsetHeight.
This doesn't seem right, `offsetWidth` rounds to integers to begin with which this code shouldn't do, but also is not defined for non-elements, so this should probably do something like:

 * If `this` is a `Document`, then you need to use the layout viewport.
 * If `this` is an `Element` or `Text` node, then you need to iterate over the fragments.

2025-08-14 15:55 UTC, emilio commented on cssom-view-1/Overview.bs
> +    - 'margin': https://drafts.csswg.org/css-box-4/#box-edges - use the margin-box
This should not just drop the urls like this, it should link to the definition. `ResizeObserver` has _very_ similar functionality, maybe crib from there?

2025-08-14 15:55 UTC, emilio commented on cssom-view-1/Overview.bs
> +    3. create a DomQuad from the rect via DOMQuad.fromRect
Proper capitalization `DOMQuad` and linking please.

2025-08-14 15:55 UTC, emilio commented on cssom-view-1/Overview.bs
> +    4. Calculate the resulting transformation matrix between the element and options.realtiveTo (if relativeTo is unset use window.defaultView) via the algorithm defined in getCompleteTransform
`window.defaultView` is not a thing, also `s/realtiveTo/relativeTo`.

This should be untransforming the rect to the layout viewport if there's no `relativeTo`.

2025-08-14 15:55 UTC, emilio commented on cssom-view-1/Overview.bs
> + 1. transform each point of the DOMQuad via convertPointFromNode
This should link to `convertPointFromNode`, but also probably should have more precise details like:

```
 * Let <var>p1</var> be the result of calling [=convertFromFromNode=] with <var>quad</var>.p1, <var>from</var> and <var>options</var>.
 * ...
 * Return a new [=DOMQuad=] with <var>p1</var>...
```

2025-08-14 15:55 UTC, emilio commented on cssom-view-1/Overview.bs
> + 1. get the resulting matrix between the node and the document.defaultView via the algorithm defined in getCompleteTransform
Give these meaningful names like:

```
 * Let <var>thisTransformToViewport</var> be the result of calling [=getCompleteTransform=] with <var>this</var> and <var>this</var>' [=associated document=].
 * Let <var>fromTransformToViewport</var> be the result of ...
 * Invert <var>fromTransformToViewport</var>.
 * ...
```

Then reference those.

2025-08-14 15:55 UTC, emilio commented on cssom-view-1/Overview.bs
> +   - 'content': x + border.leftWidth + padding.left, y + border.topWidth + padding.top
Same, refer to standard terms. It seems `ResizeObserver` refers to the CSS2 border box area, etc.

2025-08-14 15:55 UTC, emilio commented on cssom-view-1/Overview.bs
> + 4. Depending on the value of options.fromBox modify the point with the calculated style values of the element.
This should use `<var>point</var>` etc.

2025-08-27 13:09 UTC, whimboo commented
Hi @jogibear9988. Would you maybe have the time to update this PR based on the review feedback from Emilio? Thanks a lot!

2025-08-27 13:40 UTC, jogibear9988 commented
Sorry, I've read them, and hopefully fix in the next days

2025-10-30 10:55 UTC, whimboo commented
Hi @jogibear9988. I wanted to check back with you about the status of this PR. Is it still something you can continue working on? Thanks!

2025-11-23 20:50 UTC, jogibear9988 commented
@whimboo 
sorry, had not much time to work on this.
at the moment I fix my polyfill (https://github.com/jogibear9988/getBoxQuadsPolyfill) to also respect offset-.... css properties. Didn't know they exist. 
Also there is a small issue with webcomponents I try to fix.
Then I look to fix this spec.

2025-11-23 20:52 UTC, jogibear9988 commented
Also I think the spec needs an upgrade to also include a function to calculate the complete transformation matrix between two elements.
My polyfill does this, and I need this also some time in my designer, and this is not possible only with the boxQuads result.
is this something I also should add here, or should this be an extra issue/pull req?

2025-11-24 08:25 UTC, bramus commented
> Also I think the spec needs an upgrade to also include a function to calculate the complete transformation matrix between two elements. My polyfill does this, and I need this also some time in my designer, and this is not possible only with the boxQuads result. is this something I also should add here, or should this be an extra issue/pull req?

This would need a separate PR – one that would need a CSS WG Resolution first to get the group’s consensus to adding it.

2026-02-10 21:17 UTC, whimboo commented
Hello @jogibear9988. I want to check back with you if you may have some time that this PR could be moved forward? Or is it blocked based on the last comment? Thanks!

2026-03-21 00:51 UTC, Psychpsyo commented on cssom-view-1/Overview.bs
> +        subtracting the used value of 'margin-top' from {{DOMRect/y}},
These calculations are not how you get a box fragment's margin/padding/border box edges. Whether a box fragment has margins, borders and padding along any given edge depends on many factors beyond just its used values. (Whether that edge adjoins a fragmentainer break and whether or not the box is fragmented along that edge and the value of the `box-decoration-break` CSS property on that box and the value of `margin-trim` on any ancestors whose inner edge that edge touches...) I'd just say which edge the values should correspond to and that the DOMRect should be positioned so that the border edge is at 0,0 instead of trying te re-define the conversion between the different edges from first principles somehow.

2026-05-05 19:26 UTC, jogibear9988 commented on cssom-view-1/Overview.bs
> +        subtracting the used value of 'margin-top' from {{DOMRect/y}},
Thanks, that makes sense.

I changed this in the latest update. `getBoxQuads()` now defines the fragment rect in local coordinates with the border edge at 0,0, and for the `"margin"`, `"padding"`, and `"content"` cases it refers to the fragment’s corresponding box area instead of re-deriving those edges from used values.

So this should now follow the standard box definitions rather than trying to reconstruct them from first principles.

2026-05-05 19:27 UTC, jogibear9988 commented
also added some description to my polyfill: https://github.com/jogibear9988/getBoxQuadsPolyfill/blob/main/csswg-getBoxQuads-calculation.md

2026-05-05 19:38 UTC, jogibear9988 commented
I also have a new library wich uses getBoxQuads API, to be able to create screenshots or vector exports of HTML pages: https://github.com/node-projects/layout2vector

2026-06-17 07:22 UTC, whimboo commented
@jogibear9988 is this PR ready for another review? If yes, mind re-requesting review from Emilio? Thanks.

2026-06-17 07:40 UTC, jogibear9988 commented
Yeah, should be ready

2026-06-22 09:30 UTC, emilio requested changes
Thanks, this looks a lot better! Some nits and tweaks but looks good to me with those fixed.

2026-06-22 09:30 UTC, emilio commented on cssom-view-1/Overview.bs
> +    GeometryNode relativeTo; // if omitted, coordinates are relative to the layout viewport
nit: Indentation. Also the "if omitted.." should be in the spec prose

2026-06-22 09:30 UTC, emilio commented on cssom-view-1/Overview.bs
> +    DOMPoint convertPointFromNode(DOMPointInit point, GeometryNode from, optional ConvertCoordinateOptions options = {}); // result is flattened to 2D
nit: Ditto

2026-06-22 09:30 UTC, emilio commented on cssom-view-1/Overview.bs
> +box fragment, in content order.
This should be in flattened tree order, and should link to the definition.

2026-06-22 09:30 UTC, emilio commented on cssom-view-1/Overview.bs
> +    GeometryNode relativeTo; // if omitted, coordinates are relative to the layout viewport
It's already, so just remove the comment.

2026-06-22 09:30 UTC, emilio commented on cssom-view-1/Overview.bs
> +        1. Let <var>parent</var> be null.
Parent is not `parent` right? It's more of `ancestor`

2026-06-29 11:32 UTC, emilio approved these changes
I think this is in a pretty good state now. Could you squash please? Also I don't know what needs to happen to make the IPR bot happy... @svgeesus can you help?

2026-06-29 11:36 UTC, whimboo commented
> I think this is in a pretty good state now. Could you squash please? Also I don't know what needs to happen to make the IPR bot happy... @svgeesus can you help?

As it looks like @jogibear9988 needs to [join the Cascading Style Sheets (CSS) Working Group](https://www.w3.org/groups/wg/css/join). Once done it should be fine.

2026-06-29 11:56 UTC, jogibear9988 commented
Don‘t think this is so easy
https://www.w3.org/groups/wg/css/instructions/

Somebody needs to invite me

2026-06-29 20:47 UTC, Psychpsyo commented
> Don‘t think this is so easy https://www.w3.org/groups/wg/css/instructions/
> 
> Somebody needs to invite me

You can send an application to become an Invited Expert without explicitly being invited beforehand.

2026-06-30 08:45 UTC, jogibear9988 commented
I‘d send it

2026-06-30 11:33 UTC, svgeesus commented
@jogibear9988 I will send you a request for an individual IPR commitment for this PR.

(There is no need for Invited Expert for this one PR)

2026-06-30 14:56 UTC, jogibear9988 commented
> @jogibear9988 I will send you a request for an individual IPR commitment for this PR.
> 
> (There is no need for Invited Expert for this one PR)

Okay for me

2026-06-30 22:15 UTC, jogibear9988 commented
can someone retrigger the IPR check?

2026-06-30 22:17 UTC, jogibear9988 commented
and if we have this merged, what are the next steps? Is there a way to get this going forward in browsers? (for example move the API in FF away from the flag? get it implemented in chrome? (nearly every browser already has 90% of this already for the dev tools)

2026-07-01 02:29 UTC, Psychpsyo commented
> and if we have this merged, what are the next steps? Is there a way to get this going forward in browsers? (for example move the API in FF away from the flag? get it implemented in chrome? (nearly every browser already has 90% of this already for the dev tools)

For one, you can open browser bugs and write web platform tests for the feature (both of those should happen regardless). Implementing a well-tested feature that someone asked for is going to be an easier sell than just "spec says to do this". But the only thing that will definitely get this implemented in browsers is if you do the implementation yourself / pay someone to do it. There isn't much other special magic that can compel a browser vendor into doing something the spec tells them to, and every browser vendor has to prioritize between hundreds of things already.

2026-07-01 04:49 UTC, jogibear9988 commented
> > and if we have this merged, what are the next steps? Is there a way to get this going forward in browsers? (for example move the API in FF away from the flag? get it implemented in chrome? (nearly every browser already has 90% of this already for the dev tools)
> 
> For one, you can open browser bugs and write web platform tests for the feature (both of those should happen regardless). Implementing a well-tested feature that someone asked for is going to be an easier sell than just "spec says to do this". But the only thing that will definitely get this implemented in browsers is if you do the implementation yourself / pay someone to do it. There isn't much other special magic that can compel a browser vendor into doing something the spec tells them to, and every browser vendor has to prioritize between hundreds of things already.

there already exist some:
https://github.com/web-platform-tests/wpt/blob/master/css/cssom-view/cssom-getBoxQuads-001.html
https://github.com/web-platform-tests/wpt/blob/master/css/cssom-view/cssom-getBoxQuads-002.html

yeah, only wonder, firefox has it since 2014 (12 years), and kept it behind a flag since then.

2026-07-01 05:54 UTC, jogibear9988 commented
I added a few more tests:

https://github.com/web-platform-tests/wpt/pull/61015

2026-07-01 06:35 UTC, whimboo commented
@jogibear9988 I also saw that you created https://github.com/web-platform-tests/wpt/pull/50314 a while ago and which is still open and not reviewed. Is that PR up-to-date so that we could try to see it reviewed as well?

Regarding the remaining steps for Firefox, we seem to still have a [couple of bugs open for `getBoxQuads`](https://bugzilla.mozilla.org/buglist.cgi?query_format=advanced&short_desc_type=allwordssubstr&short_desc=getBoxQuads&bugidtype=include&list_id=18028832), and possibly some related issues as well.

@emilio, could you maybe provide an overview of what would still be needed on our side to move this API out from behind the flag once this PR got landed?

2026-07-01 06:38 UTC, whimboo commented
FYI I triggered the IPR revalidation and it seems to be all fine now. Now someone with permissions is needed to get it merged.

2026-07-01 08:14 UTC, emilio commented
> @emilio, could you maybe provide an overview of what would still be needed on our side to move this API out from behind the flag once this PR got landed?

More tests would be good, but on the Gecko side the main blocker was the spec and ideally some implementation interest from other browsers, see https://bugzilla.mozilla.org/show_bug.cgi?id=2026051

2026-07-01 08:15 UTC, emilio approved these changes
Let's try this, thanks!

2026-07-01 08:15 UTC, merged

2026-07-01 08:23 UTC, jogibear9988 commented
https://bugzilla.mozilla.org/show_bug.cgi?id=1107559

2026-07-01 08:41 UTC, whimboo commented
Thanks a lot @jogibear9988 for getting it finished! It's great to see that we are closer to be able to offer support for these APIs via WebDriver BiDi (https://github.com/w3c/webdriver-bidi/issues/787).

2026-07-03 17:03 UTC, jogibear9988 commented
> > and if we have this merged, what are the next steps? Is there a way to get this going forward in browsers? (for example move the API in FF away from the flag? get it implemented in chrome? (nearly every browser already has 90% of this already for the dev tools)
> 
> For one, you can open browser bugs and write web platform tests for the feature (both of those should happen regardless). Implementing a well-tested feature that someone asked for is going to be an easier sell than just "spec says to do this". But the only thing that will definitely get this implemented in browsers is if you do the implementation yourself / pay someone to do it. There isn't much other special magic that can compel a browser vendor into doing something the spec tells them to, and every browser vendor has to prioritize between hundreds of things already.

did this:
https://chromium-review.googlesource.com/c/chromium/src/+/8039580