[mediaqueries-5] Draft text for in-gamut MQ, see https://github.com/w3c/csswg-drafts/issues/5045
w3c/csswg-drafts pull request #5523
Opened 2020-09-17 16:40 UTC by svgeesus

Has some worked examples.

Specifies a default sRGB if the output device is not known, which is fine for screens but not for printers, hence should.

2020-09-17 17:26 UTC, tabatkins commented on mediaqueries-5/Overview.bs
> +		<pre class="lang-css">@color-profile --fogra39 {
There's no need to do this sort of source contortion - you can just line up all your code properly starting on the next line, and Bikeshed'll ensure the output is good.

2020-09-17 17:26 UTC, tabatkins approved these changes

2020-09-17 21:30 UTC, alshamiri5 approved these changes

2020-09-18 11:08 UTC, svgeesus commented
@florian thoughts?

2020-09-30 08:11 UTC, frivoal commented
I think the write up is clear and precise, so it gives a clear understanding of how this works.

However, I think it's missing an explanation of why you'd want to use this, and what kind of situations it's for. The reason I think this may be important is that I suspect this is an easy thing to misunderstand, and to use when you didn't need to, or to fail to notice that it could be applicable to problems you have.

If I'm understanding things correctly, most of the time, the right way to deal with out of gamut colors is not to use this, and instead to reach for [rendering-intent](https://drafts.csswg.org/css-color-4/#descdef-color-profile-rendering-intent). This would be a more specialized tool, that you'd typically use when developing something like a photo editor or something of the sort, where you'd want to display a bright color as a warning if some of the colors end up out of gamut or something. But if it's that, I'm not completely sure why you'd want to check against the gamut of the output device. Checking against so selected target color space that you intent to save your edited image into would make more sense to me. More over, if that's the case, I'd guess this would be most useful not just with raw colors whose value you specify directly, but with colors process through one or more layers of the `color-adjust()` function for colors-5. The syntax description suggests you can do that, but the examples don't show case it.

The fogra39 input being checked against a high-end 7 color printer output almost makes sense as a use case, as that would let you soft-proof something before printing it, showing clear warnings if something would go off. But I don't think that would quite work either, given that as far as I know, CSS User Agents (at least mainstream ones known as browsers) never render to a printer with a specific color space, but always render to PDF, which by itself doesn't have a clearly bounded color space, and so the answer of the query would always be true. Maybe I am misunderstanding this too and it would actually work for some reason that escapes me, or maybe it would indeed only work in a not-a-browser CSS-UA, but then it should be called out in order not to lure people into thinking it would work in browsers while in reality it wouldn't.

Also, whether it's for soft proofing or for image editing, it also feels it would be very useful if in addition to be able to test single colors, you could pass an `<<image>>`, and get to know if any part of the image would be out of gamut.

Depending on what the actual use cases are, I wonder if the fact that you cannot test whether a color / image is in gamut after having been through a [css filter](https://drafts.fxtf.org/filter-effects/#FilterProperty) may be limiting. Whether that's a sign that I don't understand the use cases, or that this is an incomplete tool, I don't know.


Either way, even though I feel I understand **how** it works, I am reasonably confused as to the applicability of this feature. I think we need to have a bit of a description of what this is or isn't for, and to change or expand the examples to relate them not just to the calculation itself, but to actual situations you'd want to use this in.

2020-09-30 08:50 UTC, faceless2 commented
I can't speak for most of this, but you mentioned PDF and my ears started burning...

Generally I'd agree with Florian's statement that PDF can represent any color in any color-space, so would always return true here. There are specific situations where that might not be the case, but they're always going to be user-agent specific - for example, a PDF can be created with an "Output Intent" color-space, which describes the intended printing conditions for the PDF. This concept used with both PDF/A or PDF/X. Targeting a specific Output Intent is possible with several of the CSS to PDF engines.

It's possible you _might_ want to ensure all colors are within that color-space when you're generating the PDF, but this is a decision based on the intended use of the PDF by whoever is making it. It's not a hard requirement based on the file format.  Specifying an Output Intent is fairly common. Limiting colors to only be within that Output Intent is less common.

What's more common in PDF is disallowing a particular color-space entirely - for example, disallowing all RGB colors, or everything but CMYK. The "in-gamut" test wouldn't really help here; a media-query for this would need to look more like
`@media (colorspace:display-p3)`, so it could be used to select between RGB and CMYK bitmap images (for example). This query would be "can I accept content in this colorspace". However that's obviously a different issue to the one under discussion.

2020-09-30 09:36 UTC, frivoal requested changes
Marking as requesting changes, based on https://github.com/w3c/csswg-drafts/pull/5523#issuecomment-701235855

2020-12-17 13:57 UTC, closed without merging

2021-01-18 01:46 UTC, frivoal commented
@svgeesus did you close this because you agreed with my skeptical feedback, or did this move some place else?

2021-01-20 12:36 UTC, svgeesus commented
Because we were all told off for creating branches in this repo, which messes with the GitHub <-> Mercurial synchronization; and since this PR didn't look like it would be accepted anyway.

2021-03-17 16:44 UTC, LeaVerou commented
> Because we were all told off for creating branches in this repo, which messes with the GitHub <-> Mercurial synchronization; and since this PR didn't look like it would be accepted anyway.

So is there a different PR somewhere for this, so that we could iterate?

2021-03-17 17:53 UTC, tabatkins commented
And if might be useful to read <https://www.xanthir.com/b4hf0> if you want to still do the PR from your personal fork

2021-03-18 08:12 UTC, frivoal commented
@svgeesus Regardless of git branching shenanigans, I'd be curious to hear your response to https://github.com/w3c/csswg-drafts/pull/5523#issuecomment-701235855. I usually feel I have a decent grasp on colors, as evidenced by generally agreeing with you, who definitely know what you're talking about. But here we seem to be in disagreement, so I'm puzzled :)

2021-03-18 15:59 UTC, LeaVerou commented
@frivoal The way I see it, the use cases are:

1. More granular detection of the output device's color gamut than the [`color-gamut`](https://drafts.csswg.org/mediaqueries/#color-gamut) media feature.
2. More control over fallback in cases where you don't want to depend on the UA's default gamut mapping algorithm