[css-fonts-5] Don't allow more than 2 values for the font-size @font-face descriptor
w3c/csswg-drafts pull request #6162
Opened 2021-03-30 21:45 UTC by litherum

The prose says what to do if there are exactly 1 or exactly 2 values, but not what to do if there are more. `#` indicates that there can be more.

2021-03-30 22:49 UTC, tabatkins commented
These aren't the same grammar. `<<number>>#` is comma-separated repetitions, `<<number>> <<number>>?` isn't.

However, I suspect that "no commas" is what's wanted here, right?

2021-03-30 23:43 UTC, svgeesus requested changes
Shouldn't this be [{1,2}](https://drafts.csswg.org/css-values-4/#component-multipliers) ?

2021-03-31 01:11 UTC, litherum commented
Right. The other descriptors don’t accept commas, so I don’t think this one should either.

2021-04-02 05:52 UTC, svgeesus approved these changes

2021-04-02 05:53 UTC, merged