[scroll-animations-1] Add note about horizontal and vertical axis still using logical direction
w3c/csswg-drafts pull request #8667
Opened 2023-03-31 19:00 UTC by flackr

Fixes #8665

2023-03-31 20:16 UTC, ydaniv commented
For me, in general, this follows expected behavior, so a general SGTM.

2023-04-13 16:54 UTC, flackr commented
@fantasai, does this seem reasonable to add?

2023-04-14 18:54 UTC, fantasai requested changes
- s/may/can/ since we're not granting RFC2119 permission here. :)
- Move the note up to right after the DL, since it's a user-facing note clarifying the stuff in the DL and the following two paragraphs are rather less interesting to users.
- This brings up an interesting question about how we measure progress for `align-content: end`...

2023-04-14 18:56 UTC, fantasai commented on scroll-animations-1/Overview.bs
> +	which may flip depending on writing mode.
Possible rewrite:

```suggestion
	Note: Progress is in reference to the [=scroll origin=],
	which can flip depending on [=writing mode=],
	even when ''scroll-timeline-axis/horizontal'' or ''scroll-timeline-axis/vertical'' is specified.
```

2023-04-20 20:05 UTC, flackr commented
Thanks for the review, I like your edit and moved the note just after the dl as suggested.

2023-04-24 20:07 UTC, fantasai approved these changes
Wfm, but I think you need to rebase over the latest spec. :/

2023-04-25 21:25 UTC, merged