[css-backgrounds-4] Added `background-layer` property
w3c/csswg-drafts pull request #9084
Opened 2023-07-18 21:10 UTC by SebastianZ

This adds a `background-layer` property as a shorthand for everything related to background layers excluding `background-color`.

It follows the resolution of https://github.com/w3c/csswg-drafts/issues/8726#issuecomment-1611761835.

Note that I went with `background-layer` for now. The name might still change, which is discussed in #9083.
Also, this change is based on the [split of the CSS Backgrounds 4 spec.](https://github.com/w3c/csswg-drafts/pull/9048) into two specs.

Fixes #8726

Sebastian

2023-09-13 19:18 UTC, fantasai requested changes
I apparently reviewed this a month ago, and then forgot to hit submit on the comments. :/

2023-09-14 09:35 UTC, SebastianZ commented on css-backgrounds-4/Overview.bs
> +		Name: background-layer
Done. (Just kept the IDs as "background-layer".)

2023-09-14 09:36 UTC, SebastianZ commented on css-backgrounds-4/Overview.bs
> +	is that it doesn't set the 'background-color'.
Yes, that's better. Changed it accordingly.

2023-09-14 09:45 UTC, SebastianZ commented on css-backgrounds-4/Overview.bs
> +	</div>
Ok, switched to a more realistic example and changed the description to be more purpose-focused.

2023-09-14 09:46 UTC, SebastianZ commented on css-backgrounds-4/Overview.bs
> +	</div>
All good points. Thanks! I have changed the example accordingly.

2023-09-14 09:46 UTC, SebastianZ commented on css-backgrounds-4/Overview.bs
> +		the background image. For that to work, 'background' needs
Done.

2023-09-14 09:47 UTC, SebastianZ commented
@fantasai I've incorporated your comments. Could you please give it another review?

Sebastian

2023-11-12 00:13 UTC, SebastianZ commented
As I've incorporated @fantasai's remarks quite a while back and didn't get any more feedback, I go ahead and merge this.

Sebastian

2023-11-12 00:14 UTC, merged