[css-ui-4] Add 'form-sizing' property
w3c/csswg-drafts pull request #9251
Opened 2023-08-28 06:03 UTC by tkent-google

See https://github.com/w3c/csswg-drafts/issues/7542

2023-08-28 06:34 UTC, tkent-google commented
My plan is that more detailed behavior is described in the HTML standard.

2023-08-28 19:13 UTC, tabatkins commented
Per <https://github.com/w3c/csswg-drafts/issues/7542#issuecomment-1685352461>, the names "normal" and "auto" aren't very illuminating here. (And, notably, as defined here they appear to be the exact opposite of what I expected them to be - I expected "normal" to be the legacy half-replaced behavior, while "auto" was the new 'act like other elements' behavior. That's a good argument for the names being bad!)

Maybe we should go with `legacy | auto` then? `auto` still isn't any clearer, but `legacy` clearly points to "how form elements *used to* size", so `auto` must be the new behavior. `legacy | normal` would also be fine.

2023-08-29 05:49 UTC, tkent-google commented
@tabatkins Let's discuss keywords in https://github.com/w3c/csswg-drafts/issues/7542

2023-10-06 06:29 UTC, tkent-google commented
Updated this PR for `fixed | content`.
https://github.com/w3c/csswg-drafts/issues/7542#issuecomment-1747803316

@frivoal would you take a loot at this please?

2023-10-12 12:53 UTC, frivoal approved these changes

2023-10-12 13:28 UTC, frivoal requested changes
Unless I am missing something, it seems to me that we'd be better off expressing the difference between the two modes in terms of intrinsic size rather than talking directly about the preferred size properties. That gets the desired effect into all aspects of sizing, which is my understanding of the groups resolution.

I've made suggested edits implementing that change. Let me know if you think these work, or if I missed subtlety you were deliberately introducing by using the proposed wording.

2023-10-12 13:28 UTC, frivoal commented on css-ui-4/Overview.bs
> +	[=preferred size property=] is 'auto'.
```suggestion
	whose [=intrinsic size=] is fixed regardless of the size of its content.
```

2023-10-12 13:28 UTC, frivoal commented on css-ui-4/Overview.bs
> +			[=preferred size property=] value is 'auto'.
```suggestion
			For [=element with default preferred size=],
			the UA must apply set the [=intrinsic size=]
			to the default preferred size defined by the host language for that element.
```

2023-10-12 13:28 UTC, frivoal commented on css-ui-4/Overview.bs
> +			The UA must not apply the default preferred size to an element.
```suggestion
			The UA must determine the element's [=intrinsic size=] based on its content,
			and must ignore any default preferred size defined by the host language for that element.
```

2023-10-13 05:49 UTC, tkent-google commented
> I've made suggested edits implementing that change. 

Thanks! I accepted all your suggestions.

2023-10-27 06:04 UTC, tkent-google commented
@frivoal  would you take a loot at this again please?

2023-10-27 06:55 UTC, frivoal approved these changes

2023-10-27 07:00 UTC, merged