[cssom] Add a “disable a CSS style sheet” definition
w3c/csswg-drafts pull request #9414
Opened 2023-09-26 15:54 UTC by sideshowbarker

2023-09-28 16:16 UTC, zcorpan commented
How is it different from [removing](https://drafts.csswg.org/cssom/#remove-a-css-style-sheet ) (and then creating a new sheet when enabling again)?

In WebKit it seems the re-enabled sheet is the same object, but in Chrome and Firefox it's a new object. Demo for http://software.hixie.ch/utilities/js/live-dom-viewer/ : 
```html
<!DOCTYPE html>
<link rel=stylesheet href="data:text/css,html{background:yellow} " id=x> 
<script>
onload = () => {
var sheet = x.sheet;
w(document.styleSheets.length)
x.disabled = true;
w(sheet.ownerNode)
w(document.styleSheets.length)
x.disabled = false;
w(sheet === x.sheet);
}
</script>
```

2023-10-09 18:57 UTC, emilio requested changes
So this doesn't match how browsers behave with `<link rel=stylesheet disabled>` right? In particular that doesn't mess with the `disabled` flag at all.

Maybe call this "remove a CSS style sheet" or so?

2023-10-09 18:57 UTC, emilio commented on cssom-1/Overview.bs
> + <a for=CSSStyleSheet>owner node</a> and <a for=CSSStyleSheet>owner CSS rule</a> to null.
How can a top level sheet have an owner CSS rule? I think that's not necessary.

2023-10-09 18:57 UTC, emilio commented on cssom-1/Overview.bs
> + <li>Set the <a>disabled flag</a>.
Probably `to true`?

2023-10-20 05:24 UTC, sideshowbarker commented
Yeah, I’m going ahead and closing 

> How is it different from [removing](https://drafts.csswg.org/cssom/#remove-a-css-style-sheet) (and then creating a new sheet when enabling again)?

I can see now that it’s not different from removing, so I’m going ahead and closing this PR.

2023-10-20 05:24 UTC, closed without merging