[selectors-4] Replace <an+b> with <an-b>
w3c/csswg-drafts pull request #9552
Opened 2023-11-02 08:07 UTC by cdoublev

Fixes #9494. 

Depends on #9480.

2023-11-20 20:09 UTC, fantasai requested changes
A few comments but also a question about bikeshedding: as we're getting further away from the actual form of the notation "2n+1", it's getting more confusing to refer to the notation. An+B was somewhat understandable, because it pattern-matches against the notation. But `<an-b>` just seems like weird 1970s computer garbage naming.

Some possible replacements:
* `<An-B>` at least helps it parse as three components (a, n, b), rather than two (an, b).
* `<ith>` or `<index>` or something like that
* other ideas?

2023-11-20 20:09 UTC, fantasai commented on selectors-4/Overview.bs
> +	which is a <<complex-real-selector-list>>,
```suggestion
	their <a>inclusive siblings</a> that match the <a>selector list</a> <<complex-real-selector-list>>,
```

or 

```suggestion
	their <a>inclusive siblings</a> that match the <<complex-real-selector-list>>,
```

as mentioned above.

2023-11-21 11:24 UTC, cdoublev commented
Marking this PR as a draft while there are discussions to rename `<an-b>`.

2026-06-11 02:33 UTC, cdoublev commented
a9805fb

2026-06-11 02:33 UTC, closed without merging