[css-images-4][editorial] Add wpt annotations, fix #9800
w3c/csswg-drafts pull request #9801
Opened 2024-01-15 19:27 UTC by svgeesus

![image](https://github.com/w3c/csswg-drafts/assets/2506926/df036e8a-066b-4b46-aaa8-a9eb38bed8ef)

Adds 3281 tests to the test results.

Note: inline test results are open in this PR, to make checking easier. Editors may well choose to set them to closed after merging this PR

@tabatkins @fantasai @LeaVerou

2024-01-15 22:31 UTC, LeaVerou requested changes
LGTM, see minor formatting issue

2024-01-15 22:31 UTC, LeaVerou commented on css-images-4/Overview.bs
> +	image-set/image-set-calc-x-rendering-2.html
Looks like there's a formatting issue here?

2024-01-15 22:31 UTC, LeaVerou commented on css-images-4/Overview.bs
> +	</wpt>
```suggestion
	<wpt>
		image-set/image-set-all-options-invalid.html
		image-set/image-set-calc-x-rendering-2.html
		image-set/image-set-calc-x-rendering.html
		image-set/image-set-computed.sub.html
		image-set/image-set-conic-gradient-rendering.html
		image-set/image-set-content-rendering.html
		image-set/image-set-dpcm-rendering.html
		image-set/image-set-dpi-rendering-2.html
		image-set/image-set-dpi-rendering.html
		image-set/image-set-dppx-rendering.html
		image-set/image-set-empty-url-rendering.html
		image-set/image-set-first-match-rendering.html
		image-set/image-set-linear-gradient-rendering.html
		image-set/image-set-negative-resolution-rendering-2.html
		image-set/image-set-negative-resolution-rendering-3.html
		image-set/image-set-negative-resolution-rendering.html
		image-set/image-set-no-res-rendering-2.html
		image-set/image-set-no-res-rendering.html
		image-set/image-set-no-url-rendering.html
		image-set/image-set-parsing.html
		image-set/image-set-radial-gradient-rendering.html
		image-set/image-set-rendering-2.html
		image-set/image-set-rendering.html
		image-set/image-set-repeating-conic-gradient-rendering.html
		image-set/image-set-repeating-linear-gradient-rendering.html
		image-set/image-set-repeating-radial-gradient-rendering.html
		image-set/image-set-resolution-001.html
		image-set/image-set-resolution-002.html
		image-set/image-set-resolution-003.html
		image-set/image-set-type-first-match-rendering.html
		image-set/image-set-type-rendering-2.html
		image-set/image-set-type-rendering-3.html
		image-set/image-set-type-rendering.html
		image-set/image-set-type-skip-unsupported-rendering.html
		image-set/image-set-type-unsupported-rendering-2.html
		image-set/image-set-type-unsupported-rendering.html
		image-set/image-set-unordered-res-rendering.html
		image-set/image-set-zero-resolution-rendering-2.html
		image-set/image-set-zero-resolution-rendering.html
	</wpt>
```

2024-01-15 22:32 UTC, LeaVerou approved these changes

2024-01-15 22:32 UTC, merged

2024-01-16 20:32 UTC, tabatkins commented
Sorry for not reviewing, was on vacation. Looks good, thanks for the review @LeaVerou!